"""Add two_factor_method column and two_factor_challenges table

Revision ID: 310384f0a839
Revises: c822385c694a
Create Date: 2026-09-12 20:53:15.626121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310384f0a839'
down_revision: Union[str, None] = 'c822385c694a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('two_factor_challenges',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('email','sms')", name='ck_2fa_challenge_method'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_challenges_id'), 'two_factor_challenges', ['id'], unique=True)
    op.create_index(op.f('ix_two_factor_challenges_user_id'), 'two_factor_challenges', ['user_id'], unique=False)
    op.add_column('users', sa.Column('two_factor_method', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_method')
    op.drop_index(op.f('ix_two_factor_challenges_user_id'), table_name='two_factor_challenges')
    op.drop_index(op.f('ix_two_factor_challenges_id'), table_name='two_factor_challenges')
    op.drop_table('two_factor_challenges')
    # ### end Alembic commands ###
