"""Add academic structure: regions, counties, institutions, schools, courses, units, academic_years, semesters, enrollments, memberships

Revision ID: 4176e5e06c7d
Revises: a71a869f922d
Create Date: 2026-09-12 15:14:11.432154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4176e5e06c7d'
down_revision: Union[str, None] = 'a71a869f922d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=True)
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=True)
    op.create_table('academic_structure_audit',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_structure_audit_entity_id'), 'academic_structure_audit', ['entity_id'], unique=False)
    op.create_index(op.f('ix_academic_structure_audit_entity_type'), 'academic_structure_audit', ['entity_type'], unique=False)
    op.create_index(op.f('ix_academic_structure_audit_id'), 'academic_structure_audit', ['id'], unique=True)
    op.create_index(op.f('ix_academic_structure_audit_user_id'), 'academic_structure_audit', ['user_id'], unique=False)
    op.create_table('counties',
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'name', name='uq_county_region_name')
    )
    op.create_index(op.f('ix_counties_code'), 'counties', ['code'], unique=True)
    op.create_index(op.f('ix_counties_id'), 'counties', ['id'], unique=True)
    op.create_index(op.f('ix_counties_region_id'), 'counties', ['region_id'], unique=False)
    op.create_table('institutions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('county_id', sa.String(length=36), nullable=False),
    sa.Column('parent_institution_id', sa.String(length=36), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','active','suspended','deactivated')", name='ck_institution_status'),
    sa.CheckConstraint("type IN ('UNIVERSITY','COLLEGE','TVET','POLYTECHNIC','KMTC','OTHER')", name='ck_institution_type'),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_institution_code')
    )
    op.create_index(op.f('ix_institutions_code'), 'institutions', ['code'], unique=False)
    op.create_index(op.f('ix_institutions_county_id'), 'institutions', ['county_id'], unique=False)
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=True)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_index(op.f('ix_institutions_parent_institution_id'), 'institutions', ['parent_institution_id'], unique=False)
    op.create_index(op.f('ix_institutions_type'), 'institutions', ['type'], unique=False)
    op.create_table('academic_years',
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('upcoming','active','completed','archived')", name='ck_academic_year_status'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_academic_year_institution_name')
    )
    op.create_index(op.f('ix_academic_years_id'), 'academic_years', ['id'], unique=True)
    op.create_index(op.f('ix_academic_years_institution_id'), 'academic_years', ['institution_id'], unique=False)
    op.create_table('schools',
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','inactive')", name='ck_school_status'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='uq_school_institution_code'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_school_institution_name')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=True)
    op.create_index(op.f('ix_schools_institution_id'), 'schools', ['institution_id'], unique=False)
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=False)
    op.create_table('courses',
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','inactive')", name='ck_course_status'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='uq_course_school_code')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=True)
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_index(op.f('ix_courses_school_id'), 'courses', ['school_id'], unique=False)
    op.create_table('semesters',
    sa.Column('academic_year_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('upcoming','active','completed','archived')", name='ck_semester_status'),
    sa.CheckConstraint('number IN (1,2,3)', name='ck_semester_number'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'number', name='uq_semester_year_number')
    )
    op.create_index(op.f('ix_semesters_academic_year_id'), 'semesters', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_semesters_id'), 'semesters', ['id'], unique=True)
    op.create_table('student_enrollments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('academic_year_id', sa.String(length=36), nullable=False),
    sa.Column('semester_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','completed','withdrawn','suspended')", name='ck_enrollment_status'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'academic_year_id', 'semester_id', name='uq_student_enrollment_period')
    )
    op.create_index(op.f('ix_student_enrollments_academic_year_id'), 'student_enrollments', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_course_id'), 'student_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_id'), 'student_enrollments', ['id'], unique=True)
    op.create_index(op.f('ix_student_enrollments_institution_id'), 'student_enrollments', ['institution_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_semester_id'), 'student_enrollments', ['semester_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_user_id'), 'student_enrollments', ['user_id'], unique=False)
    op.create_table('units',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year_level', sa.Integer(), nullable=True),
    sa.Column('semester_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','inactive')", name='ck_unit_status'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'code', name='uq_unit_course_code')
    )
    op.create_index(op.f('ix_units_course_id'), 'units', ['course_id'], unique=False)
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=True)
    op.create_index(op.f('ix_units_name'), 'units', ['name'], unique=False)
    op.create_table('unit_memberships',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('semester_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','completed','withdrawn')", name='ck_unit_membership_status'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'unit_id', 'semester_id', name='uq_unit_membership')
    )
    op.create_index(op.f('ix_unit_memberships_id'), 'unit_memberships', ['id'], unique=True)
    op.create_index(op.f('ix_unit_memberships_semester_id'), 'unit_memberships', ['semester_id'], unique=False)
    op.create_index(op.f('ix_unit_memberships_unit_id'), 'unit_memberships', ['unit_id'], unique=False)
    op.create_index(op.f('ix_unit_memberships_user_id'), 'unit_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_memberships_user_id'), table_name='unit_memberships')
    op.drop_index(op.f('ix_unit_memberships_unit_id'), table_name='unit_memberships')
    op.drop_index(op.f('ix_unit_memberships_semester_id'), table_name='unit_memberships')
    op.drop_index(op.f('ix_unit_memberships_id'), table_name='unit_memberships')
    op.drop_table('unit_memberships')
    op.drop_index(op.f('ix_units_name'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_index(op.f('ix_units_course_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_student_enrollments_user_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_semester_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_institution_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_course_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_academic_year_id'), table_name='student_enrollments')
    op.drop_table('student_enrollments')
    op.drop_index(op.f('ix_semesters_id'), table_name='semesters')
    op.drop_index(op.f('ix_semesters_academic_year_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_courses_school_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_index(op.f('ix_schools_institution_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_academic_years_institution_id'), table_name='academic_years')
    op.drop_index(op.f('ix_academic_years_id'), table_name='academic_years')
    op.drop_table('academic_years')
    op.drop_index(op.f('ix_institutions_type'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_parent_institution_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_county_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_code'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_counties_region_id'), table_name='counties')
    op.drop_index(op.f('ix_counties_id'), table_name='counties')
    op.drop_index(op.f('ix_counties_code'), table_name='counties')
    op.drop_table('counties')
    op.drop_index(op.f('ix_academic_structure_audit_user_id'), table_name='academic_structure_audit')
    op.drop_index(op.f('ix_academic_structure_audit_id'), table_name='academic_structure_audit')
    op.drop_index(op.f('ix_academic_structure_audit_entity_type'), table_name='academic_structure_audit')
    op.drop_index(op.f('ix_academic_structure_audit_entity_id'), table_name='academic_structure_audit')
    op.drop_table('academic_structure_audit')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
