"""admin auth batch

Revision ID: e1a6574a87d8
Revises: 310384f0a839
Create Date: 2026-09-13 07:55:35.803660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a6574a87d8'
down_revision: Union[str, None] = '310384f0a839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_logs',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('jurisdiction_type', sa.String(length=32), nullable=True),
    sa.Column('jurisdiction_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_action_actor', 'admin_action_logs', ['actor_id'], unique=False)
    op.create_index('ix_admin_action_created', 'admin_action_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_actor_id'), 'admin_action_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_id'), 'admin_action_logs', ['id'], unique=True)
    op.create_index('ix_admin_action_target', 'admin_action_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('admin_invitations',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('jurisdiction_type', sa.String(length=32), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=36), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_invitations_email'), 'admin_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_admin_invitations_id'), 'admin_invitations', ['id'], unique=True)
    op.create_index(op.f('ix_admin_invitations_token_hash'), 'admin_invitations', ['token_hash'], unique=True)
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=True)
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_admin_invitations_token_hash'), table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_id'), table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_email'), table_name='admin_invitations')
    op.drop_table('admin_invitations')
    op.drop_index('ix_admin_action_target', table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_actor_id'), table_name='admin_action_logs')
    op.drop_index('ix_admin_action_created', table_name='admin_action_logs')
    op.drop_index('ix_admin_action_actor', table_name='admin_action_logs')
    op.drop_table('admin_action_logs')
    # ### end Alembic commands ###
