"""Add student group tables

Revision ID: e3d87d47bcdf
Revises: 809838633a0d
Create Date: 2026-09-12 19:39:04.171267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d87d47bcdf'
down_revision: Union[str, None] = '809838633a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('academic_year_id', sa.String(length=36), nullable=False),
    sa.Column('semester_id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('forming','active','suspended','archived')", name='ck_group_status'),
    sa.CheckConstraint("subscription_status IN ('trial','active','expired','cancelled')", name='ck_group_subscription_status'),
    sa.CheckConstraint("visibility IN ('private','public','invitation_only')", name='ck_group_visibility'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'course_id', 'semester_id', 'name', name='uq_group_context_name')
    )
    op.create_index(op.f('ix_groups_academic_year_id'), 'groups', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_groups_course_id'), 'groups', ['course_id'], unique=False)
    op.create_index(op.f('ix_groups_creator_id'), 'groups', ['creator_id'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=True)
    op.create_index(op.f('ix_groups_institution_id'), 'groups', ['institution_id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.create_index(op.f('ix_groups_school_id'), 'groups', ['school_id'], unique=False)
    op.create_index(op.f('ix_groups_semester_id'), 'groups', ['semester_id'], unique=False)
    op.create_index(op.f('ix_groups_unit_id'), 'groups', ['unit_id'], unique=False)
    op.create_table('group_activities',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('virtual_link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("activity_type IN ('study_session','revision','project','social','event','other')", name='ck_activity_type'),
    sa.CheckConstraint("status IN ('scheduled','in_progress','completed','cancelled')", name='ck_activity_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_activities_group_id'), 'group_activities', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_activities_id'), 'group_activities', ['id'], unique=True)
    op.create_table('group_announcements',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('published_by', sa.String(length=36), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('normal','important','critical')", name='ck_announcement_priority'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_announcements_group_id'), 'group_announcements', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_announcements_id'), 'group_announcements', ['id'], unique=True)
    op.create_table('group_meetings',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('virtual_link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled','in_progress','completed','cancelled')", name='ck_meeting_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_meetings_group_id'), 'group_meetings', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_meetings_id'), 'group_meetings', ['id'], unique=True)
    op.create_table('group_memberships',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','active','suspended','left','removed')", name='ck_membership_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_membership')
    )
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_id'), 'group_memberships', ['id'], unique=True)
    op.create_index(op.f('ix_group_memberships_user_id'), 'group_memberships', ['user_id'], unique=False)
    op.create_table('group_officials',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.String(length=30), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('term_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('term_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('appointed_by', sa.String(length=36), nullable=True),
    sa.Column('election_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("position IN ('leader','secretary','treasurer','unit_representative')", name='ck_official_position'),
    sa.CheckConstraint("status IN ('active','expired','removed')", name='ck_official_status'),
    sa.ForeignKeyConstraint(['appointed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_officials_group_id'), 'group_officials', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_officials_id'), 'group_officials', ['id'], unique=True)
    op.create_index(op.f('ix_group_officials_position'), 'group_officials', ['position'], unique=False)
    op.create_index(op.f('ix_group_officials_user_id'), 'group_officials', ['user_id'], unique=False)
    op.create_table('group_timetables',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approval_status IN ('pending','approved','rejected')", name='ck_timetable_approval_status'),
    sa.CheckConstraint("type IN ('official','revision')", name='ck_timetable_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_timetables_group_id'), 'group_timetables', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_timetables_id'), 'group_timetables', ['id'], unique=True)
    op.create_table('group_meeting_attendees',
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('invited','accepted','declined','attended','absent')", name='ck_attendee_status'),
    sa.ForeignKeyConstraint(['meeting_id'], ['group_meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_attendee')
    )
    op.create_index(op.f('ix_group_meeting_attendees_id'), 'group_meeting_attendees', ['id'], unique=True)
    op.create_index(op.f('ix_group_meeting_attendees_meeting_id'), 'group_meeting_attendees', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_group_meeting_attendees_user_id'), 'group_meeting_attendees', ['user_id'], unique=False)
    op.create_table('group_timetable_approvals',
    sa.Column('timetable_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['group_timetables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timetable_id', 'user_id', name='uq_timetable_approval')
    )
    op.create_index(op.f('ix_group_timetable_approvals_id'), 'group_timetable_approvals', ['id'], unique=True)
    op.create_index(op.f('ix_group_timetable_approvals_timetable_id'), 'group_timetable_approvals', ['timetable_id'], unique=False)
    op.create_index(op.f('ix_group_timetable_approvals_user_id'), 'group_timetable_approvals', ['user_id'], unique=False)
    op.create_table('group_timetable_entries',
    sa.Column('timetable_id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['group_timetables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_timetable_entries_id'), 'group_timetable_entries', ['id'], unique=True)
    op.create_index(op.f('ix_group_timetable_entries_timetable_id'), 'group_timetable_entries', ['timetable_id'], unique=False)
    op.drop_constraint('password_resets_token_hash_key', 'password_resets', type_='unique')
    op.drop_index('ix_password_resets_token_hash', table_name='password_resets')
    op.create_index(op.f('ix_password_resets_token_hash'), 'password_resets', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_resets_token_hash'), table_name='password_resets')
    op.create_index('ix_password_resets_token_hash', 'password_resets', ['token_hash'], unique=False)
    op.create_unique_constraint('password_resets_token_hash_key', 'password_resets', ['token_hash'])
    op.drop_index(op.f('ix_group_timetable_entries_timetable_id'), table_name='group_timetable_entries')
    op.drop_index(op.f('ix_group_timetable_entries_id'), table_name='group_timetable_entries')
    op.drop_table('group_timetable_entries')
    op.drop_index(op.f('ix_group_timetable_approvals_user_id'), table_name='group_timetable_approvals')
    op.drop_index(op.f('ix_group_timetable_approvals_timetable_id'), table_name='group_timetable_approvals')
    op.drop_index(op.f('ix_group_timetable_approvals_id'), table_name='group_timetable_approvals')
    op.drop_table('group_timetable_approvals')
    op.drop_index(op.f('ix_group_meeting_attendees_user_id'), table_name='group_meeting_attendees')
    op.drop_index(op.f('ix_group_meeting_attendees_meeting_id'), table_name='group_meeting_attendees')
    op.drop_index(op.f('ix_group_meeting_attendees_id'), table_name='group_meeting_attendees')
    op.drop_table('group_meeting_attendees')
    op.drop_index(op.f('ix_group_timetables_id'), table_name='group_timetables')
    op.drop_index(op.f('ix_group_timetables_group_id'), table_name='group_timetables')
    op.drop_table('group_timetables')
    op.drop_index(op.f('ix_group_officials_user_id'), table_name='group_officials')
    op.drop_index(op.f('ix_group_officials_position'), table_name='group_officials')
    op.drop_index(op.f('ix_group_officials_id'), table_name='group_officials')
    op.drop_index(op.f('ix_group_officials_group_id'), table_name='group_officials')
    op.drop_table('group_officials')
    op.drop_index(op.f('ix_group_memberships_user_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_group_meetings_id'), table_name='group_meetings')
    op.drop_index(op.f('ix_group_meetings_group_id'), table_name='group_meetings')
    op.drop_table('group_meetings')
    op.drop_index(op.f('ix_group_announcements_id'), table_name='group_announcements')
    op.drop_index(op.f('ix_group_announcements_group_id'), table_name='group_announcements')
    op.drop_table('group_announcements')
    op.drop_index(op.f('ix_group_activities_id'), table_name='group_activities')
    op.drop_index(op.f('ix_group_activities_group_id'), table_name='group_activities')
    op.drop_table('group_activities')
    op.drop_index(op.f('ix_groups_unit_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_semester_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_school_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_institution_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_creator_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_course_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_academic_year_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
